/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymtemp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class CustomerDash extends javax.swing.JFrame {
    
    String uName;
    /**
     * Creates new form CustomerDash
     * @param uName
     */
    public CustomerDash(String uName) {
        initComponents();
        this.uName = uName;
        pp.doClick();
        
                
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namef = new javax.swing.JTextField();
        idf = new javax.swing.JTextField();
        trainerf = new javax.swing.JTextField();
        hallf = new javax.swing.JTextField();
        planf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trainer :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 63, 33));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 63, 33));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 63, 33));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Plan :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 63, 33));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hall : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 63, 33));

        namef.setBackground(new java.awt.Color(102, 102, 102));
        namef.setForeground(new java.awt.Color(255, 255, 255));
        namef.setBorder(null);
        jPanel1.add(namef, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 150, -1));

        idf.setBackground(new java.awt.Color(102, 102, 102));
        idf.setForeground(new java.awt.Color(255, 255, 255));
        idf.setBorder(null);
        jPanel1.add(idf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 150, -1));

        trainerf.setBackground(new java.awt.Color(102, 102, 102));
        trainerf.setForeground(new java.awt.Color(255, 255, 255));
        trainerf.setBorder(null);
        trainerf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerfActionPerformed(evt);
            }
        });
        jPanel1.add(trainerf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 150, -1));

        hallf.setBackground(new java.awt.Color(102, 102, 102));
        hallf.setForeground(new java.awt.Color(255, 255, 255));
        hallf.setBorder(null);
        jPanel1.add(hallf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 150, -1));

        planf.setBackground(new java.awt.Color(102, 102, 102));
        planf.setForeground(new java.awt.Color(255, 255, 255));
        planf.setBorder(null);
        jPanel1.add(planf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 150, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 120, 27));

        pp.setBackground(new java.awt.Color(240, 240, 239));
        pp.setBorder(null);
        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });
        jPanel1.add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 374, -1, -1));

        tt1.setColumns(20);
        tt1.setRows(5);
        tt1.setBorder(null);
        jScrollPane1.setViewportView(tt1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 310, 230));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 120, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Modify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 100, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 150, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 150, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 150, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 150, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymtemp/images/icons8_Delete_50px.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 40, 40));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dashboard");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 280, 60));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Workout:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 150, 50));

        jButton3.setBackground(new java.awt.Color(153, 255, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymtemp/images/icons8_Undo_50px_1.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(51, 51));
        jButton3.setMinimumSize(new java.awt.Dimension(51, 51));
        jButton3.setPreferredSize(new java.awt.Dimension(51, 51));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 670));

        setBounds(500, 200, 1193, 675);
    }// </editor-fold>//GEN-END:initComponents

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        try{
            String sql = "select * from customers where name = ? ";
            PreparedStatement ps;
            Connection conn = new DBConnection().connect();
        
            ps = conn.prepareStatement(sql);
            ps.setString(1,uName);
            ResultSet rs = ps.executeQuery();
            
            /*namef.setEditable(false);
            planf.setEditable(false);
            idf.setEditable(false);
            trainerf.setEditable(false);
            hallf.setEditable(false);*/
            rs.next();
            namef.setText(rs.getString("name"));
            idf.setText(rs.getString("id"));
            planf.setText(rs.getString("plan"));
            trainerf.setText(rs.getString("trainer"));
            hallf.setText(rs.getString("hall"));
            
            tt1.setEditable(false);
            tt1.append("Equipment \t Time \n");
            
            sql = "select * from plan where pid = ? ";
            ps = conn.prepareStatement(sql);
            ps.setString(1,rs.getString("plan"));
            rs = ps.executeQuery();
            
            while(rs.next()){
                tt1.append(rs.getString("eqid")+"\t"+rs.getString("time")+"\n");
            }
            
        } catch (SQLException ex) {
            System.out.println("faliure");
        }
    }//GEN-LAST:event_ppActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement ps;
        Connection conn = new DBConnection().connect();
        ResultSet rs1 = null, rs2 = null, rs3 = null;
        try{
            String sql1 = "Select * from trainers ";
            
            
            ps = conn.prepareStatement(sql1);
            
            
            rs1 = ps.executeQuery();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error: "+e);
        }
        try{
            String sql1 = "Select * from hall ";
            
            
            ps = conn.prepareStatement(sql1);
            
            
            rs2 = ps.executeQuery();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error: "+e);
        }
        try{
            String sql1 = "Select * from plan ";
            
            
            ps = conn.prepareStatement(sql1);
            
            
            rs3 = ps.executeQuery();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error: "+e);
        }
        int flag = 0;
        try{
            while(rs1.next())
            {
                if(rs1.getString("id").equals(trainerf.getText())){
                    flag++;
                    break;
                }
            }
            while(rs2.next())
            {
                if(rs2.getString("hallid").equals(hallf.getText())){
                    flag++;
                    break;
                }
            }
            while(rs3.next())
            {
                if(rs3.getString("pid").equals(planf.getText())){
                    flag++;
                    break;   
                }
            }
            if(flag == 3 && namef.getText() != null && idf.getText() != null){
                String sql = "delete from customers where name = ? ";
                ps = conn.prepareStatement(sql);
                ps.setString(1,uName);
                ps.executeUpdate();
                sql = "select pass from cust where name = ?";
                ps = conn.prepareStatement(sql);
                ps.setString(1,uName);
                ResultSet rs = ps.executeQuery();
                rs.next();
                String passs = rs.getString("pass");
                sql = "delete from cust where name = ? ";
                ps = conn.prepareStatement(sql);
                ps.setString(1,uName);
                ps.executeUpdate();
                
                new addcusfnc().addToCustomerDetails(namef.getText(),idf.getText(),planf.getText(),hallf.getText(),trainerf.getText());
                new signupfnc().addTosignDetails(uName,passs,0);
            }
            else{
                JOptionPane.showMessageDialog(null, "Not gg", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
            System.out.println("failure");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PreparedStatement ps;
        Connection conn = new DBConnection().connect();
        try{
            String sql = "delete from customers where name = ? ";
            ps = conn.prepareStatement(sql);
            ps.setString(1,uName);
            ps.executeUpdate();
            
            sql = "delete from cust where name = ? ";
            ps = conn.prepareStatement(sql);
            ps.setString(1,uName);
            ps.executeUpdate();
            
            new Login().setVisible(true);
            this.hide();
            
        }catch(SQLException e){
            System.out.println("failure");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void trainerfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainerfActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Login().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDash("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hallf;
    private javax.swing.JTextField idf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField namef;
    private javax.swing.JTextField planf;
    private javax.swing.JButton pp;
    private javax.swing.JTextField trainerf;
    private javax.swing.JTextArea tt1;
    // End of variables declaration//GEN-END:variables
}
